.gitignore, Gemfile
- allow using a specified GEM_SOURCE
- allow a local location for puppet versus installed
- Search for and load Gemfile.local
=> (FM-2442) Gemfile improvements

Gemfile, tests/acceptance/pre-suite/00_puppet_agent_install.rb, tests/integration/pre-suite/00_pe_install.rb, tests/test_run_scripts/all_acceptance_tests_w2008r2.sh, tests/test_run_scripts/all_acceptance_tests_w2012r2.sh, tests/test_run_scripts/all_integration_tests_w2008r2.sh, tests/test_run_scripts/all_integration_tests_w2012r2.sh
With Beaker 2.16.0 the installation methods for PE have changed slightly.
The pre-suites, Gemfile and test run scripts have been updated to address
the changes.
=> (MODULES-2198) Update Tests for New Beaker Version

tests/acceptance/tests/basic_dsc_resources/dsc_before_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/dsc_require_puppet_type.rb, tests/acceptance/tests/basic_functionality/alternate_path_separator.rb, tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_debug_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_noop_dsc_manifest.rb, tests/lib/dsc_utils.rb
Update the "test_dsc_resource" method to throw assertion failures.
=> (MODULES-2201) Update Helper Method

tests/acceptance/tests/basic_dsc_resources/group/group_valid_members.rb, tests/manifests/basic_dsc_resources/dsc_single_resource.pp.erb
Add a test that verifies that a user can specify an array for a DSC resource
parameter.
=> (MODULES-2263) Add Test for DSC Resources with Array

tests/acceptance/tests/basic_dsc_resources/registry/reg_remove_value.rb
Update the registry test for ensure "absent" now that the fix in place.
=> (MODULES-2285) Update Registry "absent" Test

lib/puppet/provider/templates/invoke_dsc_resource.ps1.erb
Missed two lines when removing the code that sets the LCM RefreshMode.
Removed.
=> (MODULES-2291) Remove last LCM Changes

tests/acceptance/tests/basic_dsc_resources/service/negative/service_incompatible_startup_state.rb, tests/acceptance/tests/basic_dsc_resources/service/negative/service_invalid_ensure.rb, tests/acceptance/tests/basic_dsc_resources/service/negative/service_invalid_name.rb
Add negative tests cases for the "service" DSC resource type.
=> (MODULES-2336) Create Tests for Basic DSC Resource "Service"

tests/acceptance/tests/basic_dsc_resources/file/dir_recurse.rb, tests/acceptance/tests/basic_dsc_resources/file/dir_remove_dir.rb, tests/acceptance/tests/basic_dsc_resources/file/dir_valid_path.rb, tests/acceptance/tests/basic_dsc_resources/file/dir_valid_unicode_path.rb, tests/acceptance/tests/basic_dsc_resources/file/file_remove_file.rb, tests/acceptance/tests/basic_dsc_resources/file/file_valid_path_contents.rb, tests/acceptance/tests/basic_dsc_resources/file/file_valid_path_source.rb, tests/acceptance/tests/basic_dsc_resources/file/file_valid_unicode_contents.rb, tests/acceptance/tests/basic_dsc_resources/file/file_valid_unicode_path.rb, tests/acceptance/tests/basic_dsc_resources/file/file_valid_unicode_source.rb, tests/acceptance/tests/basic_dsc_resources/file/negative/file_invalid_force.rb, tests/acceptance/tests/basic_dsc_resources/file/negative/file_invalid_path.rb, tests/acceptance/tests/basic_dsc_resources/file/negative/file_invalid_sourcepath.rb
Add tests for "File" DSC resource type.
=> (MODULES-2286) Create Tests for Basic DSC Resource "File"

README.md
Updated readme with relevant information
=> (MODULES-2265) Readme updates

CHANGELOG.md, metadata.json
The initial Puppet Labs release of the DSC module.
=> (FM-3134) release updates for 0.8.0

CHANGELOG.md
Add the changes and the initial msutter releases to the
Changelog.
=> (FM-3134) Update changelog

README.md
Add notes on the log resource and how it can be enabled under
known issues.
=> (MODULES-2449) Log resource may appear not to work

tests/acceptance/tests/basic_dsc_resources/environment/env_delete_var.rb, tests/acceptance/tests/basic_dsc_resources/environment/env_new_var.rb, tests/acceptance/tests/basic_dsc_resources/environment/env_no_value.rb, tests/acceptance/tests/basic_dsc_resources/environment/env_update_path_var.rb, tests/acceptance/tests/basic_dsc_resources/environment/env_update_var.rb
Create acceptance tests for the "Environment" DSC resource type.
=> (MODULES-2501) Add Tests for "Environment" DSC Resource

tests/acceptance/tests/basic_dsc_resources/windowsprocess/negative/process_invalid_path.rb, tests/acceptance/tests/basic_dsc_resources/windowsprocess/process_kill.rb, tests/acceptance/tests/basic_dsc_resources/windowsprocess/process_valid_args.rb
Add tests for the "WindowsProcess" DSC resource.
=> (MODULES-2398) Create Tests for "WindowsProcess" Resource

tests/acceptance/tests/basic_dsc_resources/user/negative/user_invalid_passwordneverexpires.rb, tests/acceptance/tests/basic_dsc_resources/user/negative/user_invalid_username.rb, tests/acceptance/tests/basic_dsc_resources/user/user_remove.rb
Create acceptance tests for the DSC basic resource type "user". [skip-ci]
=> (MODULES-2229) Add Tests for DSC "User" Resource

tests/acceptance/tests/basic_dsc_resources/file/dir_valid_path.rb, tests/acceptance/tests/basic_dsc_resources/group/group_remove.rb, tests/acceptance/tests/basic_dsc_resources/group/group_unicode_groupname.rb, tests/acceptance/tests/basic_dsc_resources/group/negative/group_add_non-existent_user.rb, tests/acceptance/tests/basic_dsc_resources/group/negative/group_invalid_groupname.rb, tests/acceptance/tests/basic_dsc_resources/group/negative/group_member_conflict.rb, tests/lib/dsc_utils.rb
Create acceptance tests for the "Group" DSC resource type.
=> (MODULES-2523) Add Tests for "Group" Resource Type

README.md
Add the sub headings in the Usage section that are not present in the TOC
=> (docs)(MODULES-2568) Fix and clean up Readme headings

README.md
Some examples for using DSC Resources other than the Website are needed.
Add the following examples:
- Registry
- File
=> (docs)(MODULES-2250) Document a Few DSC Data Types

tests/acceptance/tests/basic_dsc_resources/group/group_unicode_groupname.rb, tests/acceptance/tests/basic_dsc_resources/user/negative/user_invalid_password.rb, tests/acceptance/tests/basic_dsc_resources/user/user_valid_password.rb, tests/acceptance/tests/basic_dsc_resources/user/user_valid_unicode.rb, tests/lib/dsc_utils.rb, tests/manifests/basic_dsc_resources/dsc_single_resource.pp.erb
Create acceptance tests for DSC resources that use a "PSCredential" parameter
data type. This PR needs #93 merged first. DO NOT MERGE.
=> (MODULES-2537) Add Tests for "PSCredential"

tests/acceptance/tests/basic_dsc_resources/user/negative/user_invalid_password.rb
Fix for the empty password acceptance test. [skip ci]
=> (MODULES-2661) Fix Broken "User" Resource Test

tests/integration/tests/user_scenarios/negative/blacklist_xchrome.rb, tests/integration/tests/user_scenarios/negative/blacklist_xfirefox.rb
Add acceptance tests (integration) for black listed DSC resources. [skip-ci]
=> (MODULES-2700) Add Black List Acceptace Tests

README.md
Initial feedback suggests that someone without direct knowledge of DSC will not know how to use our module because they do not know how to find information on how to use DSC. We should add some links to the quickstarts on Technet and some of the official PowerShell team blog posts
=> (MODULES-2519) Places for More DSC Information

README.md
- Suggest users employ environments to prevent installs on 2003
=> (MODULES-2668) Document Windows 2003 LFN issues

build/dsc/manager.rb, types.md
List all the generated DSC types in a markdown table format that is
easier to read. Also, group by DSC Resource Module so its easier to find
resources by the module they are in.
=> (MODULES-2520) List all DSC Types in Table Format

README.md
Remove uneeded TOC header for the References section
=> (MODULES-2520) Fix Reference TOC

tests/integration/tests/user_scenarios/duplicate_different_module_version.rb, tests/integration/tests/user_scenarios/duplicate_same_module_version.rb
Add tests for duplicated modules on the $PSModulePath.
[skip ci]
=> (MODULES-2743) Add Duplicate Module Tests

README.md
In preparing the documentation for upcoming release:
- Add missing link for Usage scenario - Handling Reboots
- Notes is now Development
- Development section added
- Contributors section added
cc @jbondpdx / @Iristyle
=> (FM-3921)(doc) Update documentation

README.md
Ready for review and (hopefully) merge!
=> dsc module README edit for review

README_BUILD.md
=> (MODULES-2891) Clarify building documentation

.gitignore, .sync.yml, Gemfile, appveyor.yml, spec/spec_helper.rb
~~This should come after we pull in https://github.com/puppetlabs/puppetlabs-dsc/pull/132~~
=> (maint) update modulesync files

CHANGELOG.md, metadata.json
- Add release notes and bump version in metadata.json
=> (FM-4990) Prepare 1.0.1 DSC release

.sync.yml, CONTRIBUTING.md, Gemfile, LICENSE, MAINTAINERS.md, NOTICE, appveyor.yml
The PR contains the updates from the new modsync config for windows;
- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup
https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61
=> (maint) modsync update - master

CHANGELOG.md, CONTRIBUTING.md, README.md, README_BUILD.md, metadata.json
Update all references from puppetlabs to puppet
=> (PA-285) Branding name change

lib/puppet/provider/base_dsc/powershell.rb
Increase the timeout to 20 minutes for all DSC executions
=> (MODULES-3342) Increase execution timeout

README.md
This updates the readme with recently discovered known issues with the
Registry DSC Resource and with the WMF 5.1 release
=> (maint) Update readme with new known issues

build/dsc/manager.rb
- Hard fail during a rake dsc:build when duplicate CIM class
definitions appear in MOF schemas.  Output includes a full report of
the duplicates, sorted by resource name and a full list of paths
containing duplicates.
=> (maint) Detect duplicate import MOF schema names

CHANGELOG.md, metadata.json
Update changelog and metadata.json for release
=> (FM-5713) Update metadata.json and changelog

.sync.yml, Gemfile
https://github.com/puppetlabs/modulesync_configs/pull/104
=> Workaround frozen strings on ruby 1.9

README.md
This was an old ticket in my backlog that never made it into a sprint, one line docs change.
cc: @jbondpdx
=> (MODULES-3178)(docs) Add known issue to README

CHANGELOG.md, metadata.json
This commit updates the Changelog and Metadat for the 1.3.0 release of the DSC
module.
=> (MODULES-4629) Release 1.3.0

CHANGELOG.md
This commit updates the changelog to reflect the additional changes for the
April DSC release.
=> (MODULES-4629) Update Changelog for April 2017 DSC Release

CHANGELOG.md
=> (doc) Correct 1.3 release Changelog date

CHANGELOG.md
- Changelog updated to include a fix for the improper packaging of the
1.3.0 release.
No other changes
=> (MODULES-5537) Prepare for 1.3.1 release

CHANGELOG.md, metadata.json
=> Prep for v1.4.1 release

tests/test_run_scripts/acceptance_tests.sh, tests/test_run_scripts/integration_tests.sh
update tests to point to new internal gem host
=> (RE-9941) Migrate from stickler to artifactory

CHANGELOG.md
This commit updates the CHANGELOG to follow the KeepAChangeLog format.
=> (MODULES-6636) Keep a Changelog

CHANGELOG.md, metadata.json
This commit updates the changelog and metadata.json for the 1.5 release
=> (MODULES-5549) Update changelog and metadata for v1.5

metadata.json
Version number string was incorrect.
=> (MAINT) Fix Version Number

build/dsc.rake, build/dsc.rb, build/dsc/documentbuilder.rb, build/dsc/manager.rb, build/dsc/typebuilder.rb, build/dsc/typecleaner.rb, build/dsc/typeimporter.rb
The PR is purely maintenance work and introduces no new features, but it does remove an unused task and extracts a lot of code to ruby classes that were previously sitting free flowing inside rake tasks.  This will reduce pain in the future when we modify this to pull DSC Resources from sources other than git.
Commit 7f0876e7 is most important, and could be considered a bugfix all on it's own, as it standardizes the variables that control folder placement inside both the rake task and inside the manager.rb class. Previously these were hardcoded, but gave the impression that they could be separately controlled when in fact it was possible to specify a new path in the rake task but have it ignored by the manager.rb class. 
This PR also renames some global variables and some local variables …
=> (maint) Pay down tech debt

build/dsc/psmodule.rb, build/dsc/resource.rb, spec/spec_helper.rb, spec/unit/build/dsc/resource_spec.rb
This commit fixes the code that finds the psd1 manifest file for a given
DSC Resource.
A psd1 manifest is assumed to be the same name as the DSC Resource. However
on case sensitive OS, the file name could be a different case than the DSC
Resource name, i.e SqlServerDsc vs SQLServerDsc.ps1, which would cause
File.exists? to fail to find the file even though it exists.
Dir.glob is used here to find any psd1 manifest in the module_dir folder.
This is a safe assumption because by convention there can only be one
manifest file for a DSC Resource because it follows PowerShell Module
manifest conventions. To address cases where there are more than one
psd1 file in a DSC Resource directory, we filter on module name,
lowercased.
If both methods have failed to find a psd1 manifest,
then we truly do …
=> (MODULES-7063) Fix case sensitive psd1 search

CHANGELOG.md, metadata.json
This commit updates the CHANGELOG and metadata.json for the 1.6
release.
=> (MODULES-7058) Update metdata for 1.6 release

CHANGELOG.md, metadata.json
This commit updates the module in preparation for a v1.7.0 release.
=> (MODULES-8063) Prepare module for 1.7.0 release

CHANGELOG.md, metadata.json
Reverts puppetlabs/puppetlabs-dsc#379
=> Revert "(MODULES-8063) Prepare module for 1.7.0 release"

spec/integration/puppet_x/puppetlabs/compatible_powershell_version_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb, spec/integration/puppet_x/puppetlabs/powershell_version_spec.rb
to facilitate more complete test output from our unit tests.
=> (WIN-280) add skip() unless pattern to tests

spec/acceptance/basic_dsc_resources/file/file_valid_spec.rb
This PR fixes the acceptance test after merging PR https://github.com/puppetlabs/puppetlabs-dsc/pull/351
=> Fix file validation acceptance tests for Unicode

.sync.yml, .travis.yml, Gemfile, metadata.json
"MODULES-10236 disable deploy_to_forge for the module"
pdk version: `1.14.1`
=> pdksync - "MODULES-10236 disable deploy_to_forge for the module"

.github/workflows/release.yml, .sync.yml, .travis.yml, Gemfile, metadata.json
"(IAC-365) updating tokens and dataset for honeycomb"
pdk version: `1.16.0`
=> (IAC-365) updating tokens and dataset for honeycomb
