Gemfile
- Prior to this change, tests could execute under Ruby 1.9.3,
but failed under Ruby 2 in our CI environment with:
Running tests
rake aborted!
LoadError: cannot load such file -- iconv
/tmp/tmp.egwevqY6m1/ruby/2.1.0/gems/mof-1.2.2/lib/mof/scanner.rb:22:in `require'
- This change includes the iconv gem on Ruby 2+ platforms so that
tests may be executed.  It's possible that the mof gem will
later feature updates to make it a Ruby 1.9.3+ gem that will no
longer require iconv, but this workaround fixes the issue for now
=> (maint) Ensure CI can execute against Ruby 2

Gemfile
The "master_manipulator" gem is private so the Gemfile should only load the gem
when the private mirror is available.
=> (FM-2916) Fix Gemfile Issue with master_manipulator

Gemfile
Use PuppetLabs's mof repo with required fixes until the fixes have been
accepted in the mof maintainer's repo and a new version of the gem has
been cut.
=> (MODULES-2121) Use Modified Mof Repo

lib/puppet_x/msutter/templates/set_dsc_configuration.erb, lib/puppet_x/msutter/templates/test_dsc_configuration.erb
If a user tries to run the module on a Windows system running WMF 5
errors will occur when applying manifests with DSC resources specified:
~~~
Error: /Stage[main]/Main/Dsc_file[tmp_folder]: Could not
evaluate: WARNING: The configuration 'PuppetConfiguration' is loading
one or more
built-in resources without explicitly importing associated modules. Add
Import-DscResource -ModuleName 'PSDesiredStateConfiguration' to your
configuration to avoid this message.
False
~~~
Without this fix the warning will continue to occur producing nothing
to move forward with in setting the configuratin.
=> (FM-2783) Fix Module Failure on WMF5 base resources

tests/acceptance/pre-suite/02_configure_lcm.rb, tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb
The single acceptance test is failing because FM-2783 was resolved, but
MODULES-1960 has yet to be implemented.
=> (FM-2932) Fix Failing Acceptance Test

tests/acceptance/tests/basic_dsc_resources/dsc_before_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/dsc_require_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb, tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb
Add tests that verify simple resource behavior of DSC resource types
in a Puppet manifest.
=> (FM-2624) Add Basic DSC Resource Tests

Gemfile, tests/test_run_scripts/all_integration_tests_w2008r2.sh, tests/test_run_scripts/all_integration_tests_w2012r2.sh
The test run scripts for integration tests point to the old name for SG and
need to be updated to point to the renamed package repository. Also, the
Gemfile has been updated to use the latest version of Beaker as well as the
public version of "master_manipulator".
=> (MODULES-2223) Update Integration Test Run Scripts

tests/acceptance/tests/basic_dsc_resources/dsc_before_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/dsc_require_puppet_type.rb, tests/acceptance/tests/basic_functionality/alternate_path_separator.rb, tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_debug_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_dsc_manifest.rb, tests/integration/tests/basic_functionality/puppet_agent_noop_dsc_manifest.rb, tests/lib/dsc_utils.rb
The "test_dsc_resource" method will be renamed to "assert_dsc_resource" to make it clear that it throws assertion exceptions.
=> (MODULES-2201) Rename DSC Test Helper Method

tests/acceptance/pre-suite/01_dsc_module_install.rb, tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb, tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb
The acceptance tests install the DSC module using PMT on Windows agent nodes
which no longer works because of PUP-4854. The pre-suite has been updated
to utilize a shorter root path for module unpacking.
Also, two other tests were changed to skip since the breaking behavior for
errored DSC resources has changed. The tests never passed to begin with so
nothing has really changed.
=> (MODULES-2236) Enable Work-a-round for Path Length Issue

build/dsc/templates/dsc_type.rb.erb, lib/puppet/type/dsc_archive.rb, lib/puppet/type/dsc_environment.rb, lib/puppet/type/dsc_file.rb, lib/puppet/type/dsc_group.rb, lib/puppet/type/dsc_log.rb, lib/puppet/type/dsc_package.rb, lib/puppet/type/dsc_registry.rb, lib/puppet/type/dsc_script.rb, lib/puppet/type/dsc_service.rb, lib/puppet/type/dsc_user.rb, lib/puppet/type/dsc_windowsfeature.rb, lib/puppet/type/dsc_windowsprocess.rb, lib/puppet_x/msutter/templates/invoke_dsc_resource.erb, lib/puppet_x/msutter/templates/mof.erb
- Fix a bug in the logic around when to specify a module version when
generating PowerShell code.
- Also, after some discussion, decided to use the presence / absence
of dscmeta_module_version to determine whether to use module name or
module name + version. In the code generation for specific types - in
this case PSDesiredStateConfiguration - omit dscmeta_module_version.
After some discussion it was decided since these resources are not
vendored, and can vary based on the operating system version that the
Puppet module is installed on, that we should be less strict around
requesting a particular version.  It's possible that minor .z
versions will have the same interface, but may include OS specific
bugfixes, etc.  Hardcoding a single version number is too inflexible
given these DSC types …
=> (MODULES-1960) Don't version in-OS resources

build/dsc/templates/dsc_type.rb.erb, build/dsc/templates/dsc_type_spec.rb.erb, lib/puppet/provider/base_dsc/powershell.rb, lib/puppet/type/dsc_file.rb, lib/puppet/type/dsc_group.rb, lib/puppet/type/dsc_package.rb, lib/puppet/type/dsc_registry.rb, lib/puppet/type/dsc_service.rb, lib/puppet/type/dsc_xarchive.rb, lib/puppet/type/dsc_xdhcpserveroption.rb, lib/puppet/type/dsc_xdnsserveraddress.rb, lib/puppet/type/dsc_xdnsserversecondaryzone.rb, lib/puppet/type/dsc_xdnsserverzonetransfer.rb, lib/puppet/type/dsc_xfirewall.rb, lib/puppet/type/dsc_xgroup.rb, lib/puppet/type/dsc_xiismodule.rb, lib/puppet/type/dsc_xjeaendpoint.rb, lib/puppet/type/dsc_xjeatoolkit.rb, lib/puppet/type/dsc_xpackage.rb, lib/puppet/type/dsc_xremotefile.rb, lib/puppet/type/dsc_xservice.rb, lib/puppet/type/dsc_xsmbshare.rb, lib/puppet/type/dsc_xsqlhagroup.rb, lib/puppet/type/dsc_xvhdfile.rb, lib/puppet/type/dsc_xvmhyperv.rb, lib/puppet/type/dsc_xwebsite.rb, lib/puppet/type/dsc_xwindowsoptionalfeature.rb, spec/unit/puppet/type/dsc_file_spec.rb, spec/unit/puppet/type/dsc_xfirewall_spec.rb
When generating the types for each DSC Resource we were not explicitly
making any parameter that was an array in the DSC return an array in
Puppet. Puppet sometimes unwraps arrays if they only contain one item,
which does not work when the DSC Resource parameter is expecting a
string.
To fix this we munge the value to always be an array in DSC Resource type
and make sure that when the PowerShell script is compiled it uses proper
PowerShell array syntax.
Additionaly we change the spec tests to expect array notation if the
parameter is an array
=> (MODULES-2205) Fix DSC Array generation

tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_binary_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_dword_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_key.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_force_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_remove_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_binary_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_dword_hex_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_dword_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_implicit_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_key_valuename.rb, tests/lib/dsc_utils.rb, tests/manifests/basic_dsc_resources/dsc_single_resource.pp.erb
Add automated tests for the "Registry" DSC resource type. Also, update the
"dsc_utils.rb" helper library to be more better-er.
Cannot merge this until #28 is merged.
=> (MODULES-2228) Create Tests for "Registry" DSC Resource

build/dsc.rb
- The 'build' gems cannot presently be installed on Windows due to
some conflicts with 'charlock_holmes' that includes native code that
doesn't compile on Windows, and 'librarian-repo' which relies on
'rubyzip' that includes native code that doesn't compile on Windows.
This makes a typical Windows bundle install:
`bundle install --path .bundle/gems --without system_tests build`
However, the current rake tasks always try to load these gems, and
therefore rake tasks cannot run on Windows.
At a future date, some of the build process will be reworked to
run on Windows, but for now, simply guard the loading of build
related gems based on their existence.
Build tasks will not work properly on Windows, but at least other
tasks like 'spec_prep', included with puppetlabs_spec_helper, are
now …
=> (maint) Enable rake without Bundler 'build' group

tests/acceptance/pre-suite/01_puppet_agent_install.rb, tests/acceptance/tests/basic_dsc_resources/dsc_before_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/dsc_require_puppet_type.rb, tests/acceptance/tests/basic_dsc_resources/multi_failing_dsc_resources.rb, tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_binary_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_dword_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/negative/reg_invalid_key.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_force_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_remove_value.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_binary_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_dword_hex_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_dword_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_implicit_valuedata.rb, tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_key_valuename.rb, tests/acceptance/tests/basic_dsc_resources/some_failing_dsc_resources.rb, tests/acceptance/tests/basic_functionality/alternate_path_separator.rb, tests/acceptance/tests/basic_functionality/puppet_apply_debug_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_dsc_manifest.rb, tests/acceptance/tests/basic_functionality/puppet_apply_noop_dsc_manifest.rb, tests/test_run_scripts/all_acceptance_tests_w2008r2.sh, tests/test_run_scripts/all_acceptance_tests_w2012r2.sh
Some recent merges have caused the tests to go red because the affected
tests were set to expect failure. With the fixes in place the tests now need
to actually test something. Also, I updated the tests to use less "confine"
statements and remove unused variables.
=> (MODULES-2266) Fix All the Tests

tests/acceptance/tests/basic_dsc_resources/service/service_valid_name_startuptype_state.rb
Add a test for the "Service" DSC resource type that lacks the "ensure"
parameter.
=> (MODULES-2257) Create Test for Unensurable DSC Type

.gitignore, .pmtignore, .sync.yml, Gemfile, Puppetfile, Rakefile
- Librarian-puppet is completely unused in this module, so remove any
references, including related rake tasks.  The existing rake tasks
were in conflict with the usage of .fixtures.yml in
puppetlabs_spec_helper (PSH), which is the default tool uesd by
Puppet for modules.
The conflicting task also included a call to `ln -s`, rendering the
current approach incompatible with Windows. This commit restores the
ability to correctly install fixtures with PSH on Windows.
=> (maint) Remove librarian-puppet

lib/puppet/provider/templates/invoke_dsc_resource.ps1.erb
Invoke-DscResource does not respect WarningAction or WarningVariable and
so sends output to the Warning stream regardlees of user setting. This
Warning output is caught and sent back along with our objects, and
breaks the JSON parser.
We set $WarningPreference to 'SilentlyContinue' to work around this.
=> (MODULES-2388) Warning Output breaks JSON Parsing

.sync.yml, Gemfile
Using PSH with versions lower than 0.9.0 results in issues
attempting to symlink on Windows. We'll take the latest
version as the dependency since it has the best fixes
available for cross platform testing.
Rake is required by other groups, so move it from just the
development group to the default group to allow it to always
be pulled in.
=> (maint) puppetlabs_spec_helper ~>0.10.3 / rake to default group

tests/integration/tests/user_scenarios/vendored_resource.rb
Add an integration test for verifying that an end user can utilize vendored
DSC resources in manifests.
=> (MODULES-2296) Create User Scenario

build/dsc.rake
A bug in the rake task meant the cloned xDscResources did not copy over to the lib/puppet_x/dsc_resources folder. This fixes it
=> (FM-2564) Ensure rake task copies DSC resources to vendor folder

Gemfile
For Puppet older than 3.5.0 on Windows, a facter version at or under
1.7.5 should be selected for greatest compatibility when requesting
a gem puppet version and if a facter version has not been specified.
(MODULES-2452) Update Beaker Version
Update the Beaker version to use "2.20" which has an important fix for PE
installations.
=> (maint) Guarantee Facter version for old Puppets / (MODULES-2452) Update beaker version

README.md
When installing the dsc module, users can run into a long file name
(LFN) issue, because the paths of some of the schema files are quite
deep, and much deeper while puppet module tool is bringing down the
resources from the forge.
Document that the issue can occur, provide a place for users to see
updates toward a final fix, and provide a workaround for anyone that
may be affected by the issue.
Supersedes #61.
=> (MODULES-2408)(doc) Add note about long file names during install

tests/acceptance/tests/basic_dsc_resources/waitforall/negative/waitforall_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforany/negative/waitforany_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforsome/negative/waitforsome_blacklist.rb
The "WaitFor*" resources are not supported by the DSC module. This set of
tests verifies that the resources have been blacklisted by the module.
=> (MODULES-2399) Create Tests for "WaitFor*" Resources

tests/integration/tests/user_scenarios/kitchen_sink.rb, tests/lib/dsc_utils.rb, tests/manifests/user_scenarios/kitchen_sink.pp.erb
Add a test for running every available basic DSC resource type in a  single
manifest. Also, I made a small update to the "dsc_utils" helper to change
a regex to make it more strict. The change does not affect any test currently.
(I found it through visual inspection.)
=> (MODULES-2400) Create Kitchen Sink User Scenario

lib/puppet/provider/base_dsc/powershell.rb, spec/unit/puppet/provider/powershell_spec.rb
If a user specifies single quotes inside any string in a puppet manifest our module
will produce an invalid quoted string. We can fix this by properly escaping the single quote
inside the string provided.
=> (MODULES-2442) Mixing Quotes Causes Crash

README.md
- The docs should closer match style guide.
- Correct misspellings
- Remove incorrect note about composite resources.
- Fix grammar in some places.
- Add note about setting refresh mode.
Supersedes #62
=> (docs) Readme fixes

tests/acceptance/tests/basic_dsc_resources/waitforall/negative/waitforall_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforany/negative/waitforany_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforsome/negative/waitforsome_blacklist.rb
The "WaitFor*" tests are failing because they are no longer black listed.
The tests have been updated to expect the failure.
=> (MODULES-2506) Fix Failing Tests

README.md
Add documentation to the readme explaining that you cannot currently
invoke DSC Resources as a regulaer user, you need administrative
credentials.
=> (docs)(FM-2683) Document Non Admin DSC

README.md
Because DSC runs under machine scope, it uses LocalMachine Execution
Policy no matter what context the calling PowerShell process execution
policy is set at. This seems to be an undocumented but known limitation
of DSC. Document this limitation in the module.
=> (doc)(MODULES-2500) Process execution policy is ignored

tests/acceptance/pre-suite/03_configure_lcm.rb, tests/acceptance/tests/basic_functionality/negative/misconfigure_lcm.rb, tests/lib/dsc_utils.rb
Add an acceptance test for misconfiguring the LCM before running DSC manifests.
I added a new method to the "dsc_utils" helper library to allow for easy
transition between refresh modes.
=> (MODULES-2480) Create Negative Test for LCM Configuration

metadata.json
The module dependencies do not have an upper bound to the next
major version, which leaves a possibility for compatibility
issues across a major version boundary, where incompatible
changes are known to occur due to semantic versioning. It is
better to be conservative and set an upper bound, then release
a newer version once a major version has been released and found
compatible than to suddenly need to fix a broken dependency.
The lower bound of stdlib was not correct, as the version we
should have started with is 2.3.0. This is the first version that
allowed messages to be passed with validate_re. See
https://github.com/puppetlabs/puppetlabs-stdlib/commit/41b07232e464f25403a8f9c786ec0061bf6dc40e
for details.
=> (MODULES-2514) Update module dependencies

README.md
The Package DSC Resource Path parameter does not handle forward slashes
for paths. Warn the user and explain why this is so and point to a Puppet ticket
with more examples and information
=> (doc)(MODULES-2486) Warn about Forward Slashes in Paths

README.md, lib/puppet/provider/templates/invoke_dsc_resource.ps1.erb, tests/acceptance/tests/basic_functionality/allow_lcm_modes.rb
- As of the 8/31/2015 production preview release of WMF5, the global
LCM RefreshMode no longer needs to be set to 'Disabled' to apply DSC
resources.
Update the Invoke-DscResource PowerShell template to remove the check
and update documentation / tests accordingly
=> (MODULES-2575) Remove LCM Refresh Mode checks

README.md
The Package DSC Resource uses the ProductName and ProductCode to identify
if a MSI is installed, but does not tell the user where to find this
informaiton. It also refers to ProductCode as ProductId, further confusing
the issue.
~~Requires PR #95 to be merged first to have correct Usage sub headings~~
=> (docs)(MODULES-2466) Document ProductCode for Package DSC Resource

tests/integration/tests/basic_functionality/negative/dsc_on_linux.rb
The test case for testing the DSC module on linux expects a certain
error message. Since we have now constrained ourselves to only running
on systems with PowerShell 5 the error message has changed.
Update the test case with the correct error message.
=> (MODULES-2643) Fix DSC Linux Test Case

manifests/lcm_config.pp, spec/defines/lcm_config_spec.rb
Remove the ability to set the LCM RefreshMode to Pull, as it will cause
errors during execution without setting more information than we
currently support in the dsc::lcm_config type. Since this type is no
longer needed in our module, this is not a loss.
=> (MODULES-2485) Remove LCM Pull RefreshMode

lib/puppet_x/puppetlabs/dsc_type_helpers.rb, tests/acceptance/tests/basic_dsc_resources/user/negative/user_invalid_password.rb
Handle checking if a username or password is not provided better by
checking in the first iteration and not a second time.
=> (MODULES-2615) Handle Empty Passwords for PSCredentials

tests/acceptance/pre-suite/02_dsc_module_install.rb, tests/integration/pre-suite/01_dsc_module_install.rb
The pre-suites contained a bug that caused problems when attempting to
run the acceptance tests from a local git clone. [skip-ci]
=> (MODULES-2672) Fix Test Pre-suite

tests/acceptance/tests/basic_dsc_resources/waitforall/negative/waitforall_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforany/negative/waitforany_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforsome/negative/waitforsome_blacklist.rb
- WaitFor tests required modifications now that they're
blacklisted properly.
=> (MODULES-2244) Update acceptance tests

build/dsc.rake
Update rake task to remove any WaitFor DSC Resources downloaded from the
upstream DSCResources repo
=> (MODULES-2244) Remove WaitFor DSC Resources from Upstream

tests/acceptance/pre-suite/02_dsc_module_install.rb, tests/integration/pre-suite/01_dsc_module_install.rb, tests/test_run_scripts/acceptance_tests.sh, tests/test_run_scripts/integration_tests.sh
The integration and acceptance tests will attempt to always use the latest
module from the staging Forge currently. However, this will not always pickup
the latests pre-released version of the module if final releases exist. The
"MODULE_VERSION" environment variable is set by CI when pre-releases of a
module are published to the staging Forge.
=> (MODULES-2689) Update Tests to Use "MODULE_VERSION" Env Var

tests/test_run_scripts/integration_tests.sh
The build repository for PE 2015.2 specified in the test run script is out
of date. This update will set the default to use the officially released
build.
[skip-ci]
=> (MODULES-2784) Update PE Build Repo

README.md
Microsoft has a new documentation landing page on MSDN instead of
technet. While the existing links in the readme work, new content is
being posted here.
=> (MODULES-2519) Add new DSC Documents home page location

tests/acceptance/pre-suite/01_puppet_agent_install.rb, tests/test_run_scripts/acceptance_tests.sh
Update the Puppet Agent version that acceptance tests use.
[skip ci]
=> (MODULES-2589) Bump Puppet Agent Version

README.md
Add a reference and link to the types document that is automatically
generated when building the dsc_* types.
=> (MODULES-2520) Add link to Types document

build/dsc/resource.rb
The backing variable to the Name property was missing the n
=> (MODULES-2800) Resource name Property Typo

tests/integration/pre-suite/02_configure_lcm.rb
Add the "master_manipulator" reference to the integration pre-suite. This
change prevents a Beaker failure when using a subset of the pre-suite for
debugging purposes.
[skip ci]
=> (MODULES-2826) Fix Integration Pre-suite

.sync.yml, Gemfile
puppet-blacksmith depends on mime-types gem, which just released
a new version that requires Ruby 2. We require building the module
with 1.9.3 so pin the version to 2.99 which will allow using Ruby
less than 2.0.
=> (maint) Pin mime-types version to allow Ruby 1.9

tests/acceptance/pre-suite/02_dsc_module_install.rb, tests/integration/pre-suite/01_dsc_module_install.rb
The pre-suites for the tests needs to add the "reboot" module as a dependency.
[skip ci]
=> (MODULES-2870) Update Test Pre-suites

lib/puppet/provider/base_dsc/powershell.rb, lib/puppet/provider/templates/invoke_dsc_resource.ps1.erb, spec/unit/puppet/provider/powershell_spec.rb
- Previously, PowerShell provider methods were all instance methods,
but this isn't strictly necessary.  Move methods for generating the
Invoke-DscResource script to the providers class, so that they may
later be called by self.instances / self.prefetch when adding 'get'
support.
=> (maint) Move PowerShell provider methods to class

tests/acceptance/pre-suite/01_puppet_agent_install.rb, tests/test_run_scripts/acceptance_tests.sh, tests/test_run_scripts/integration_tests.sh
Update the version of Puppet Agent used for acceptance and integraction tests.
Also, I updated the integration test script to use the latest z release of PE.
[skip ci]
=> (MODULES-2829) Update Puppet Agent Version for Tests

tests/integration/tests/reboot/negative/reboot_graph_cycle.rb
The "reboot_graph_cycle.rb" test failed on PE 3.8.x. Now it is fixed!
[skip ci]
=> (MODULES-2911) Fix Broken Reboot Test

tests/acceptance/tests/basic_dsc_resources/windowsprocess/process_valid_args.rb
Modified the command used to during the test and increased the execution time
from as-fast-as-possible to just over 1 second.  This will help stop false CI
failures caused by test hosts under heavy load
=> (MODULES-2919) DSC - Intermittent failure of Windows Process Tests

README.md
If a user specifies a service as absent, when it is not running, it will
not be removed. This is because the dsc resource returns false when testing for
existence instead of true even though service exists because of the
following code `return ($State -eq "Stopped" -and $svc.Status -eq
"Stopped") -or ($svc.Status -eq "Running" -and $State -eq "Running")`
Since $state is a paramter and is defautled to 'Running', if the service
is stopped this will always return false instead of true.
If a user specifies a service as absent when the service is already not
present, it will error. This happens because we invert absent to present
to determine if resource exists. t\This causes the error because testing
for present requires a Path, but not when testing it is Absent. Since we
dont provide the …
=> (MODULES-2512) Cannot ensure absent on Service DSC Resource

metadata.json
In older versions of Puppet, there is a bug where a dependency is not
realized as installed when using "-" e.g. "puppetlabs-reboot" versus
"puppetlabs/reboot". Update to using "/" to guarantee compatibility
with older versions of Puppet.
=> (maint) Update Dependencies to use / separator

lib/facter/uses_win32console.rb, lib/puppet/provider/base_dsc/powershell.rb, lib/puppet_x/puppetlabs/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- Currently, each time a resource modification is made, the PowerShell
provider opens up new powershell.exe instance(s), makes a single
Invoke-DscResource call, then terminates.
This is a particularly expensive endeavor, since each resource
requires a minimum of one powershell.exe instance for the sake of
using Test to examine if the DSC resource is in the desired state. If
a resource needs to be added / removed / modified via the Set method
of Invoke-DscResource, then an additional instance is required.
With the working set and slow startup times of powershell.exe this
is a particularly expensive cost to pay per run.
- Add a new PowerShellManager class that supports reuse of an initially
created powershell.exe instance.  Modify the PowerShell provider to
use this helper class instead of …
=> (MODULES-2709) Reuse PowerShell instance for DSC

README.md
Either `ensure` or `dsc_ensure` can be used. Document the precedence
and what happens when you specify both. Provide a recommendation to
use `dsc_ensure` due to issues regarding `ensure => absent` reporting
success while doing nothing - this is a known issue captured in
MODULES-2966 that is now documented as well.
=> (MODULES-2381) Document ensure vs dsc_ensure

lib/puppet_x/puppetlabs/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
- Previously, run timeouts were executed on the Ruby side, which had
the side effect of allowing PowerShell code to continue to run in
the background, which could lead to a host of timing problems.
For instance, a long-running DSC invocation that entered a timeout
state on the Ruby execution side, would efectively block any
additional PowerShell code from running until it had completed.
Rework the timeout to take effect on the PowerShell side.  Create
runspaces as needed (when one does not exist, or when the previous
runspace encountered a timeout and was forcefully Disposed of).
Otherwise, reuse runspaces for performance to behave similarly to
calling ScriptBlock.invoke().
This should clear up any testing issues that have cropped up as a
result of previous runs still executing that were …
=> (MODULES-2709) Implement DSC timeout inside PS

tests/integration/tests/ensure_behavior/ensure_absent.rb, tests/integration/tests/ensure_behavior/ensure_absent_and_dsc_ensure_present.rb, tests/integration/tests/ensure_behavior/ensure_and_dsc_ensure_absent.rb, tests/integration/tests/ensure_behavior/ensure_and_dsc_ensure_present.rb, tests/integration/tests/ensure_behavior/ensure_present.rb, tests/integration/tests/ensure_behavior/ensure_present_and_dsc_ensure_absent.rb
I recently discovered that the DSC module supports both "ensure" and
"dsc_ensure" for ensurable resources. The tests exercise combinations of
both ensurable parameters.
=> (MODULES-2965) Add Tests for "ensure" VS. "dsc_ensure"

metadata.json
The minimum Puppet/PE Version is 3.8.0. Update to allow
for the newest PE version to be allowed as well.
=> (FM-3886) Fix Puppet/PE requirements

.sync.yml, Gemfile
There was a bug in master_manipulator that has been fixed which caused test
failures on PE 3.8.x. The master_manipulator gem was pinned to a known working
version which is no longer necessary.
=> (MODULES-2772) Unpin master_manipulator

.pmtignore
This commit adds extra directories to the PMT Ignore file as, build, docs and tests are
not required at runtime for DSC module.  Also added *.local to ignore local development
files.  While the addition of these files will not cause any errors, they are removed
to keep the module installation as lean as possible.
=> (MODULES-3119) Remove unncessary files from module build

README.md
Microsoft Windows Management Framework 5 (WMF 5) has been released.  This
commit updates the README.md file with information about the WMF 5.0
RTM, published by Microsoft at 2016-02-24
- Update the link to a download page
- Update the link to announcement on vendor blog
- Update to known issue section (Windows 2008 is not supported since
RTM, the list of server software not supported with WMF 5.0)
- Update to the prerequisites section
=> (doc) Update due to re-release of WMF 5.0 RTM

tests/acceptance/pre-suite/01_puppet_agent_install.rb
The acceptance tests were hardcoded to run against 1.3.2 to work-around a
Beaker limitation. The newer versions of Beaker now support installing the
latest Puppet Agent without specifying a version number. Updated the pre-suite
for acceptance tests to now automatically grab the latest version.
=> (FM-5017) Update Puppet Agent for Acceptance Tests

tests/acceptance/pre-suite/02_dsc_module_install.rb, tests/integration/pre-suite/01_dsc_module_install.rb
Update the pre-suites for acceptance and integration tests. Re-organize the
integration pre-suite so that module dependencies are only installed if
installing module from local source. Change the acceptance pre-suite to build
a PMT command-line to work-around the PUP-4866 issue.
=> (MODULES-2414) Update Test Pre-suites

README.md
This commit adds information about the --module_working_dir parameter
which can be used workaround the long filename issue that can arise
when installing this module.
Ticket: MODULES-3191 and PUP-4854
=> (doc) Update README with better LFN resolution

lib/puppet/provider/base_dsc/powershell.rb, lib/puppet_x/puppetlabs/powershell_manager.rb
- Use the CoreCLR compatible `WaitHandle.WaitOne(timeout)`
- Don't invoke `powershell.exe` with `-Sta`
=> (MODULES-3343) Nano server compatibility

.fixtures.yml
Previously, the DSC fixtures would use the latest (2.0.1) version
of Powershell instead of 1.0.6, as specified in the metadata.json.
This commit pins the powershell module to version 1.0.6 in the
fixtures.yml file as puppet_spec_helper does not correctly handle
version range strings.
=> (MODULES-3410) DSC fixtures uses incorrect PowerShell version

tests/integration/tests/user_scenarios/create_mysql_database_server.rb
- In commit 7fb9f22e1137ea92270150b0ef1ccef73307e83e resources were
regenerated and revendored.
Unfortunately the dsc_xmysqlserver type changed as a result, removing
the dsc_servicename parameter.  This invalidates the test in this
commit.
=> (MODULES-3431) Fix revendor integration failure

tests/integration/pre-suite/02_configure_lcm.rb, tests/integration/tests/user_scenarios/create_mysql_database_server.rb
The MySQL DSC resource has recently been updated to v2.x with breaking
changes.  This has caused the DSC CI pipeline to fail.  This commit
changes the acceptance test to expect to fail.  Once the MySQL DSC
Resource authors fix their module, these tests will then fail the failure
and we can reinstate them.
This commit also modifies the presuite LCM configuration to only occur
on Windows agents as it was possible to cause test failures if run on
a master agent.
=> (MODULES-3431) Fix acceptance tests for MySQL DSC resource

build/dsc/resource.rb, build/dsc/templates/dsc_type.rb.erb, build/dsc/templates/dsc_type_spec.rb.erb, lib/puppet/type/dsc_runbookdirectory.rb, lib/puppet/type/dsc_smavariable.rb, lib/puppet_x/dsc_resources/xSCSMA/DSCResources/MSFT_xRunbookDirectory/MSFT_xRunbookDirectory.psm1, lib/puppet_x/dsc_resources/xSCSMA/DSCResources/MSFT_xRunbookDirectory/MSFT_xRunbookDirectory.schema.mof, lib/puppet_x/dsc_resources/xSCSMA/DSCResources/MSFT_xSmaVariable/MSFT_xSmaVariable.psm1, lib/puppet_x/dsc_resources/xSCSMA/DSCResources/MSFT_xSmaVariable/MSFT_xSmaVariable.schema.mof, lib/puppet_x/dsc_resources/xSCSMA/xSCSMA.psd1, spec/unit/puppet/type/dsc_runbookdirectory_spec.rb, spec/unit/puppet/type/dsc_smavariable_spec.rb, types.md
Some DSC Resources use arbitrary values for `Present` or `Absent`. The
xRunbookDirectory DSC Resource in the xSCSMA module uses `Published`
and `Draft` as valid `Present` values for `Ensure`.
Modify the type building process to explicitly treat some resources as
exceptional cases by defining a custom hash for each MOF schema type.
This provides a way to identify non-standard resources easily, and a
process which will fail hard when new resources are introduced that
don't follow the model / aren't explicitly handled by the hash. It is
allowed to omit the :absent member of the hash for resource types
that are not absentable.
Move any inline special handling for enable / disable of the built-in
MOF type MSFT_WindowsOptionalFeature to this new hash, in addition to
MSFT_xRunbookDirectory. …
=> (MODULES-3363) Support arbitrary Ensure values

README.md
This commit documents the version strategy used to determine a version number
when releasing the module.  This commit also removes trailing whitespace.
=> (MODULES-3491) Describe version strategy in README

.fixtures.yml, metadata.json
The currently released version of PowerShell at v2 is now
considered compatible with DSC, so allow installing a newer
version of PowerShell when using the DSC module.
=> (MODULES-3627) Allow PowerShell dependency up to v3

.sync.yml, NOTICE, README.md, README_BUILD.md, build/dsc.rake
In commit c81a958 the DSC Resource update
process was changed to use a `dsc_resource_release_tags.yml` file to track
the versions of each DSC Resource.  This PR updates the README_BUILD.md
file to document these changes and how to rebuild all resources with the latest
version.  This PR also changes the links in the `README.md` to the
`README_BUILD.md` file to be absolute, not relative references.  This allows
people to click on this link in the Puppet Forge website and link directly into
the Github repository instead of getting a `Page not found` from the Forge.
Previously a few directory names had incorrect casing which caused
DSC Resource builds to fail on Ubuntu based linux computers.  This
PR fixes the case of these directories to the correct name.
=> (MODULES-3674) Update DSC Resource build documentation

.pmtignore
Previously some artifacts created from testing, for example Beaker, the DSC
module are accidentally added to the package during a `puppet module build`.
This commit adds log, junit and tmp to the Puppet Module Tool ignore file.
=> (maint) Add test artifacts to PMT Ignore

.pmtignore, Gemfile
Previously some artifacts created from testing, for example Beaker, the DSC
module are accidentally added to the package during a `puppet module build`.
This commit adds log, junit and tmp to the Puppet Module Tool ignore file.
modsync update for SHA 70360747
=> (maint) modulesync 70360747 and additions to PMT ignore

tests/acceptance/tests/basic_dsc_resources/waitforall/negative/waitforall_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforany/negative/waitforany_blacklist.rb, tests/acceptance/tests/basic_dsc_resources/waitforsome/negative/waitforsome_blacklist.rb, tests/integration/tests/user_scenarios/negative/blacklist_xchrome.rb, tests/integration/tests/user_scenarios/negative/blacklist_xfirefox.rb
With https://github.com/puppetlabs/puppet/commit/01db61e24 in Puppet 4.6.x+ we
see that with https://github.com/puppetlabs/puppet/blob/5fcc9b3f803b62e84287e1976a5f1a2eb6311f27/lib/puppet/pops/evaluator/runtime3_resource_support.rb#L31
the message has changed and we need to adjust the matcher to account for both
the old and new way of this message occurring.
As an example, the message for `dsc_waitforsome` when not found as
a valid type was changed from `Invalid resource type dsc_waitforsome`
to `Unknown resource type: 'dsc_waitforsome'`, causing the matching
to fail.
=> (MODULES-3764) Fix WaitForAll blacklist test

lib/puppet/provider/templates/invoke_dsc_resource.ps1.erb
- When a MOF Schema references an `EmbeddedInstance` it will typically
be a `String[]`, but can also be a String.
In the case where the `EmbeddedInstance` is just a `String`, the
PowerShell code should be passing a singular `CimInstance` instead
of a `CimInstance[]`.
An example of where this occurs is in the `MSFT_xWebsite` MOF, which
has definitions for 2 `EmbeddedInstance` types, one of which is an
array (which currently works), and one which is not:
>   [Write, EmbeddedInstance("MSFT_xWebBindingInformation")] String BindingInfo[];
>   [write, EmbeddedInstance("MSFT_xWebAuthenticationInformation"))] String AuthenticationInfo;
Without this change, a value cannot be set for AuthenticationInfo
as desired.  It currently passes to PowerShell Invoke-DscResource:
```powershell …
```
=> (maint) Correctly pass embedded instances

build/dsc.rake, build/dsc/manager.rb
Trying to build custom DSC Resources would fail from duplicate directories being copied, as well as not keeping the copied custom DSC Resources during build.
This PR fixes this by re-organizing the import method to have two sections, one for importing the official Microsoft DSC Resources and one for handling custom DSC Resources. This reduces the confusion over where the files should be at any one time.
=> (MODULES-4201) Fix building custom DSC Resources

build/dsc.rake
This fixes the case change in the official DSCResources folder name in the PowerShell/DSCResources repo. It also moves the folder names to a variable, and uses the variable in all the places it was specified before, so that it is now a change once fix
=> (MODULES-4430) Fix repo case change

README.md, README_BUILD.md
This updates the dsc module build instructions with clearer wording,
updated style and formating, and restructured to be easier to read and
comprehend.
This updates the readme style and formating to fix some visual errors.
Add a section to the README explaning how to troubleshoot applying dsc resources.
=> (MODULES-4128) Update the build readme with clearer instructions

lib/puppet/provider/base_dsc/powershell.rb, lib/puppet_x/puppetlabs/compatible_powershell_version.rb, spec/integration/puppet_x/puppetlabs/compatible_powershell_version_spec.rb
This restricts the dsc module from running on PowerShell versions less than 5
~~**NOTE** - PR #261 needs to be merged first~~
=> (Modules-4014) Restrict to Powershell v5

Rakefile
Previously, the Jenkins based CI testing called beaker directly instead of using
a standard rake task.  This commit adds two facade style rake tasks called
`acceptance_tests` and `reference_tests` as per the standard Puppet test tiering
practices.  This commit then just calls the equivalent beaker command.  In the
future these take tasks would call Rototiller etc. appropriately.
=> (MODULES-4667) Add facade rake tasks for test tiering

tests/integration/tests/reboot/reboot_no_invoke.rb
Previously the VM template used during acceptance testing had a pending
file rename operation which caused reboot based tests to fail.  This commit adds
a step to remove the offending registry key prior to testing.  This workaround
will not be required once https://tickets.puppetlabs.com/browse/IMAGES-539 is
resolved.
=> (maint) Ensure no PendingFileRenameOperations prior to reboot test

lib/puppet/provider/base_dsc/powershell.rb
This commit renames the global POWERSHELL_UPGRADE_MSG to
DSC_MODULE_POWERSHELL_MODULE_UPGRADE_MSG to avoid variable
name conflicts with other modules installed, namely powershell.
This relates to PR https://github.com/puppetlabs/puppetlabs-powershell/pull/192
=> (MODULES-5224) Fix Global Warning variable

build/dsc/templates/dsc_type.rb.erb
This commit updates the PowerShell version to the RTM version of
WMF 5.0 instead of the pre-release version it used to use.
=> (MODULES-2770) Restrict to WMF 5.0 RTM Version

README.md, manifests/lcm_config.pp
This adds a warning that we will remove the dsc::lcm_config manifest, which removes puppetlabs-powershell module and puppetlabs-stdlib.
Configuring the LCM was only necessary in the preview version of WMF 5.0, and is not needed for puppet to function with dsc in the RTM version which we moved to in MODULES-2770.
=> (MODULES-3409) Add deprecation warning for powershell and stdlib modules

Rakefile, manifests/lcm_config.pp
The Puppet Lint configuration for the log format was not working as intended and
was masking the Lint errors.  This commit removs the configuration item as it
is not needed.
This commit updates the lcm_config to use single quotes as per puppet lint style
guidelines.
=> (maint) Fix minor linting error in lcm_config

tests/test_run_scripts/acceptance_tests.sh, tests/test_run_scripts/integration_tests.sh
- Typically a bundle is already installed that includes all the gems
necessary to run Beaker based "integration" and "acceptance" tests.
So running `bundle install` is mostly unnecessary.
Furthermore, running this command with a gemset already installed
will write or alter the local `.bundle/config`, adding the line:
BUNDLE_WITHOUT: "build:test:development"
This prevents the ability to run `bundle exec rake spec` since the
Rake gem is loaded in the development group, resulting in an error:
```
bundler: failed to load command: rake (/Users/Iristyle/source/puppetlabs-dsc_lite/.bundle/gems/ruby/2.4.0/bin/rake)
Gem::Exception: can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? …
```
=> (maint) Fix (acceptance|integration)_tests.sh

lib/puppet_x/puppetlabs/powershell_manager.rb
Prior to this commit, the timeout waiting for PowerShell to start
was only 10 seconds; this was not, in practice, a long enough
period of time for multiple customers, especially when a node is
under heavy load. This commit increases the timeout to 30 seconds.
=> (MODULES-4748) Increase timeout for opening PowerShell

lib/puppet_x/puppetlabs/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Prior to this commit if a timeout occurs while waiting for the
connection to a named pipe then a zombie process is left on the
system as the code to close or kill it is never called. This commit
ensures that such zombie processes are removed before the error is
raised.
This commit also adds an RSPEC test to validate that if we try to
create a manager with an unreasonably low timeout value, that the
manager will not have time to open the pipes server and it will
fail to create the manager and further verify that no zombie
processes are left running.
Paired-with: Bill Hurt <william.hurt@puppet.com>
=> (MODULES-4748) Prevent zombie procs from timeout

.sync.yml, appveyor.yml
- Manually removed the extra modulesync addition for testing
Puppet 4.2.3 which is no longer necessary, and updated
AppVeyor accordingly.
=> (maint) Remove AppVeyor 4.2.3 Puppet testing

README.md, lib/puppet/provider/base_dsc/powershell.rb, lib/puppet_x/puppetlabs/dsc_type_helpers.rb, spec/unit/puppet_x/puppetlabs/dsc_type_helpers_spec.rb
- Previously a password could not be specified in a MSFT_Credential
based attribute of a given resource, due to strict validation that
was only allowing strings.
Sensitive was initially added in Puppet 4.6.0 and fully fleshed out
by Puppet 4.8.0. This module currently supports a minimum of
Puppet 4.7.0 and therefore users should be expected to use
Sensitive for password fields (example updated in README).
- Added new tests for type helpers demonstrating the ability for
MSFT_Credential to allow Sensitive.
=> (MODULES-5743) Support Sensitive in MSFT_Credential

.travis.yml
This commit updates the Travis config to remove the erroneous
`before_install` setting which is causing CI to fail. This
should be captured in the near future in a modsync update.
=> (MAINT) Fix travis config

CHANGELOG.md
Prior to this commit the changelog erroneously links to
MODULES-4648 instead of MODULES-4748. This commit
corrects the error.
=> (MAINT) Fix v1.4.1 changelog entry

build/dsc/psmodule.rb
This PR fixes the regex that parses the DSC Resource module manifest
files to correctly parse the module version.
A PowerShell psd1 manifest file follows the syntax for a PowerShell
hash. It allows newlines as well as semi-colons to deliminate each item
in the hash. It is not normal syntax to use semi-colons inside a hash
that is using newlines already, but it is still valid so the regex is
adjusted to accept it.
=> (MODULES-5590) Fix PowerShell Manifest Parsing semicolons

metadata.json
We released puppetlabs/reboot 2.0, which causes problems with modules
that have a dependancy set to < 2.0.0. This fix ensures the module will
resolve the dependency properly.
=> (Maint) Bump reboot dep

CHANGELOG.md
This PR ensures the changelog is up to date so the next releaser doesn't have to
go searching for the changes to do release prep.
=> (MAINT) Update changelog to note change to the reboot dep.

build/dsc.rake
This commit fixes the rake checkout task by reenabling it after the
first invocation so that it will process both xDscResource and
DscResource folders.
The rake checkout task will use the dsc_resource_tags.yml file to
checkout the correct git tag. This works the first time it's called when
processing the xDscResource folder. However since rake by default will
only run a task once, when the DscResource folder is processed next it
just skips it without error or warning. This has not popped up before
because before commit 08c8fc0705b6c7cc789f0e55cfb4463afa27fc02 we
weren't correctly updating dsc_resource_tags.yml with any HQ Dsc
Resources, so we couldn't have ever tried to pin a version.
=> (MODULES-6694) Fix rake checkout task

lib/puppet_x/templates/dsc/init_ps.ps1
The newest image for Windows 2008r2 is exhibiting different behavior
for loading .NET assemblies than we have seen in the past. The
System.Core assembly is not loaded into the PowerShell host process by
default any longer. This causes the init.ps1 script in the module to
to fail to start a Pipe Server to receive PowerShell scripts to be
executed. This change always attempts to load the System.Core
assembly prior to creating the pipe server object. Explicity loading the
assembly fixes the issue and the newest image becomes usable again.
=> (MODULES-6929) Fix Pipes Server in Windows 2008r2

build/dsc/psmodule.rb, spec/unit/psmodule_spec.rb
This commit fixes parsing the moduleversion part of the psd1 manifest
file for a DSC Resource by lowercasing each attribute before adding it
to the attribute hash. This avoids any casing differences introduced by
a DSC Resource author that differs from the string 'ModuleVersion'.
=> (MODULES-7055) Fix DSC Module Version Parsing

README.md
This commit updates the README to explain that the DSC LCM `RefreshMode`
need to be set to `Push` or `Disabled` in order for the Puppet `dsc`
module to work.
=> (MODULES-6640) Document DSC LCM RefreshMode

lib/facter/powershell_version.rb
The ruby gems project has changed the behavior of the
Gem::Version.correct? function. Previously when given nil as an argument
it would return true. Returning true from that function meant that a
call like Gem::Version.new(nil) would return an empty string for a
version number. This worked for us because when we compared versions, an
empty string was considered less than the version number we were testing
against and the code would evaluate without error.
Starting with rubygems/rubygems#2203 which
landed in gems 2.7.7, that function now returns false when given nil as
its argument, which causes Gem::Version.new(nil) to throw an error. This
is problematic for us because even though we take efforts to ensure that
only tests that can run on non windows platforms are ever run there, the
code …
=> (MODULES-7462) Fix broken type files

CHANGELOG.md
The changelog entry for fixing broken type files mistakenly
pointed to MODULES-7642 instead of MODULES-7462. This commit
updates the entry to point to the correct ticket and url.
=> (MAINT) Correct changelog entry ticket number

CHANGELOG.md, metadata.json
After a bit of a comedy of errors, the correct changelog entries are in place targeting the correct branch prior to release.
=> (MODULES-8063) Prep for 1.7.0 release

README.md
The MODULES-2500 ticket is a few years old now and it appears to still be an issue with DSC resources utilized through Puppet.  For convenience, and a direct solution in the README, I added the puppet code to set the execution policy to the most restricted that still supports dsc use through puppet.
=> Added puppet code for execution policy setting.

README.md
A customer reported to us that the snippet in the readme for handling
reboots was not correct, and would result in un wanted reboots on
nodes. This change ensures that only reboots requested by this module
are executed.
=> (MODULES-7716) Fix Readme Reboot Snippet

build/dsc.rake
Prior to this commit the build task would fail on any PowerShell
DSC module which did not have a tag in its repository which ended
in `-PSGallery`. Since our last release, this is true of multiple
modules included in the PowerShell DSC Resource module maintained
by Microsoft.
Even if a tracked version was specified the build still failed
because it checked for a tag regardless of whether the version
was tracked.
This commit updates the rake task for checkout to instead mark
the latest version as commit hash pinned for the submodule by
Microsoft if no PSGallery tags are found. This ensures that the
module code specified matches the code that Microsoft has pinned.
=> (MODULES-8389) Fix build process

CHANGELOG.md, lib/puppet/provider/base_dsc/powershell.rb, spec/unit/puppet/provider/powershell_spec.rb
Prior to this commit the provider would output the full Powershell log to be executed during debug runs. This is to ensure that we can verify exactly what will be executed. However, this also meant that credentials and other secrets could leak into the debug output, and thus also into PuppetDB logs.
This commit modifies the provider and  ERB template to ensure that methods for formatting Puppet data to be PowerShell compliant are able to take a new parameter, `redact`.
Passing this parameter will cause the script builder to redact any sensitive data it is passed. This flag is forwarded along through a helper method. This implementation allows us to reuse the code for interpolating the correct values into the PowerShell script for the actual execution and for the debug messaging.
There is …
=> (MODULES-8856) Redact debug

lib/puppet/provider/base_dsc/powershell.rb
- Previously templates were renderd in the Default.external_encoding
which would cause injection of UTF-8 content to create incorrect
strings.
For instance, the ERB template would load as IBM437, then Unicode
content would be coerced to that encoding when rendering an ERB
template.
Since manifest content is guaranteed to be UTF-8 and since the ERB
template is guaranteed to be UTF-8, enforce this in code
=> (MODULES-2310) Support Unicode parameters

CHANGELOG.md, lib/puppet/provider/base_dsc/powershell.rb, spec/unit/puppet/provider/powershell_spec.rb
This PR fixes the regression introduced in #405 if the `dsc_psdscrunascredential` parameter is used by dsc_* resources in Puppet. If this was the case, the following was part of the Powershell code Puppet generated for DSC:
`password = [PSCustomObject]@{'user' = 'some_user'; 'password' = 'secret'} # PuppetSensitive | new-pscredential`
The use of '#' as the start of the comment breaks the parsing of the Powershell code because everything after the '#' was disregarded. Also the debug log wasn't redacted because the line didn't match.
This PR fixes this by using the multiline comment syntax on a single line which generates the code as following:
`password = [PSCustomObject]@{'user' = 'some_user'; 'password' = 'secret'} <# PuppetSensitive #> | new-pscredential`
Also the match was altered in …
=> (MODULES-8856) Fix using the dsc_psdscrunascredential parameter

CHANGELOG.md, lib/puppet_x/puppetlabs/powershell_manager.rb
This commit increases the timeout for waiting on the named
pipe to open. This resolves issues where servers under
heavy load do not open the pipe quickly enough.
=> (MODULES-9085) Increase pipe timeout to 180s

lib/puppet_x/puppetlabs/powershell_manager.rb
Prior to this commit, Puppet fails while compiling C# code within init_ps.ps1 with a cryptic no implicit conversion of nil into String message.
This commit checks that the LIB environment variable contains invalid paths and fails with a useful error message.
=> (MODULES-8171) Run fails if paths in $env:lib don't exist

CHANGELOG.md, README.md
This is a documentation change to make it clear exactly what version
of PowerShell is required for the module to function. While 99% of
customers running WMF 5.0 will have a valid version, there was at least
one release that had a PowerShell version that will not support this
module and the DSC capabilities it requires.
=> (MODULES-7762) State Exact PS Version Requirement

lib/puppet_x/puppetlabs/powershell_manager.rb, spec/integration/puppet_x/puppetlabs/powershell_manager_spec.rb
Prior to this commit, the function that checks for valid paths in the
`lib` environment variable was broken. It would return true, and raise
an error if any value at all was assigned to that variable.
This commit fixes the behavior of that function and unit tests it to
prevent regressions.
=> (MODULES-9800) Fix Lib Environment Variable Check

.gitignore, .sync.yml
Previously in commit 0bf48aa73315 the PDK update removed the gitignores for the
DSC import process. This the import process would result in 1000s of files
wanting to be checked in.  This commit adds the require gitignores back into the
module.
=> (maint) Reinstate gitignore for DSC imports

lib/puppet/provider/templates/dsc/invoke_dsc_resource.ps1.erb
DateTime values should be passed along as System.DateTime objects and not pure strings, this fixes issues with `starttime` property not being handled correctly.
=> (MODULES-5623) Handle DateTime values correctly

lib/puppet_x/dsc_resources/xRemoteDesktopSessionHost/DSCResources/MSFT_xRDServer/MSFT_xRDServer.psm1
Fix typo in the xRDServer powershell module that prevents the script from executing succesfully.
=> MODULES-10117: Fix typo in xRDServer

.sync.yml, Gemfile, HISTORY.md, Rakefile, metadata.json
This adds support for the Github Changelog generator gem by:
- Adding gem to Gemfile
- Adding Rake tasks to Rakefile
- Fixing up the `1.9.3` tag in the HISTORY.md tags to allow parsing by the Changelog Generator gem
> NOTE: Normally the Gemfile and Rakefile changes would have been done by running `pdk update` after adding the necessary changes to `.sync.yml`, but in this case I have just manually added the changes as RSpec deprecated method issues were being introduced after the `pdk update`. This was going to be a bigger task to resolve and will be addressed in [MODULES-9515](https://tickets.puppetlabs.com/browse/MODULES-5915)
=> Add Github Changelog Generator gem
